-- Seed state 529 plan information with current 2024 data
INSERT INTO "state_529_plans" ("state", "state_name", "has_state_tax_deduction", "max_deduction_single", "max_deduction_married", "tax_credit_available", "tax_credit_amount", "plan_name", "plan_website", "special_features", "other_benefits", "restrictions") VALUES
('AL', 'Alabama', true, 5000, 10000, false, null, 'CollegeCounts 529', 'https://www.collegecounts529.com/', '["Direct-sold and advisor-sold options", "Low fees", "Age-based portfolios"]', 'State tax deduction for contributions', 'None'),
('AK', 'Alaska', false, null, null, false, null, 'UA College Savings Plan', 'https://www.uacollegesavings.com/', '["T. Rowe Price manages investments", "No state income tax"]', 'No state income tax to benefit from', 'None'),
('AZ', 'Arizona', true, 2000, 4000, false, null, 'AZ529', 'https://az529.gov/', '["Fidelity manages investments", "Multiple investment options"]', 'State tax deduction available', 'None'),
('AR', 'Arkansas', true, 5000, 10000, false, null, 'GIFT College Investing Plan', 'https://www.arkansas529.org/', '["Age-based and static portfolios", "Low minimum contribution"]', 'State tax deduction for contributions', 'None'),
('CA', 'California', false, null, null, false, null, 'ScholarShare 529', 'https://www.scholarshare529.com/', '["TIAA manages investments", "Low fees", "No state tax benefit"]', 'No state income tax deduction available', 'None'),
('CO', 'Colorado', true, null, null, false, null, 'CollegeInvest', 'https://www.collegeinvest.org/', '["Full state tax deduction", "Multiple plan options"]', 'Unlimited state tax deduction for contributions', 'None'),
('CT', 'Connecticut', true, 5000, 10000, false, null, 'CHET', 'https://www.aboutchet.com/', '["Fidelity manages investments", "Age-based options"]', 'State tax deduction available', 'None'),
('DE', 'Delaware', false, null, null, false, null, 'Delaware College Investment Plan', 'https://delawarecollegeinvestmentplan.com/', '["Fidelity manages investments"]', 'No state tax benefit', 'None'),
('DC', 'District of Columbia', true, 4000, 8000, false, null, 'DC College Savings Plan', 'https://dccollegesavings.com/', '["Multiple investment options"]', 'D.C. tax deduction available', 'None'),
('FL', 'Florida', false, null, null, false, null, 'Florida 529 Savings Plan', 'https://www.myfloridaprepaid.com/', '["No state income tax", "Prepaid and savings options"]', 'No state income tax to benefit from', 'None'),
('GA', 'Georgia', true, 4000, 8000, false, null, 'Path2College 529 Plan', 'https://path2college529.com/', '["TIAA manages investments"]', 'State tax deduction available', 'None'),
('HI', 'Hawaii', false, null, null, false, null, 'HI529', 'https://hi529.com/', '["Multiple investment options"]', 'No state tax benefit currently', 'None'),
('ID', 'Idaho', true, 6000, 12000, false, null, 'IDeal 529', 'https://www.idsaves.org/', '["State tax deduction", "Low fees"]', 'State tax deduction for contributions', 'None'),
('IL', 'Illinois', true, 10000, 20000, false, null, 'Bright Start/Bright Directions', 'https://www.brightstart.com/', '["High deduction limits", "Two plan options"]', 'Generous state tax deduction', 'None'),
('IN', 'Indiana', false, null, null, true, 1000, 'CollegeChoice 529', 'https://www.collegechoiceplan.com/', '["20% tax credit on contributions up to $5,000"]', 'State tax credit instead of deduction', 'Credit limited to $1,000'),
('IA', 'Iowa', true, 3785, 7570, false, null, 'College Savings Iowa', 'https://www.collegesavingsiowa.com/', '["Vanguard investment options"]', 'State tax deduction available', 'None'),
('KS', 'Kansas', true, 3000, 6000, false, null, 'Learning Quest', 'https://www.learningquest.com/', '["American Century manages"]', 'State tax deduction available', 'None'),
('KY', 'Kentucky', false, null, null, false, null, 'KY Saves 529', 'https://www.kysaves.com/', '["Multiple investment options"]', 'No state tax benefit', 'None'),
('LA', 'Louisiana', true, 2400, 4800, false, null, 'START Saving Program', 'https://www.startsaving.la.gov/', '["State matching grants available"]', 'State tax deduction and potential match', 'Income limits for matching grants'),
('ME', 'Maine', false, null, null, false, null, 'NextGen 529', 'https://www.nextgenforme.com/', '["Merrill Lynch manages"]', 'No state tax benefit', 'None'),
('MD', 'Maryland', true, 2500, 5000, false, null, 'Maryland 529', 'https://maryland529.com/', '["Two plan options", "State tax benefits"]', 'State tax deduction per beneficiary', 'Per beneficiary annual limit'),
('MA', 'Massachusetts', true, 1000, 2000, false, null, 'U.Fund', 'https://www.mefa.org/ufund', '["Fidelity manages investments"]', 'State tax deduction available', 'None'),
('MI', 'Michigan', true, 5000, 10000, false, null, 'MESP', 'https://www.misaves.com/', '["TIAA manages", "Low fees"]', 'State tax deduction available', 'None'),
('MN', 'Minnesota', true, 1500, 3000, false, null, 'Minnesota College Savings Plan', 'https://www.mnsaves.org/', '["TIAA manages"]', 'State tax deduction or credit', 'Subject to income limits'),
('MS', 'Mississippi', true, 10000, 20000, false, null, 'MACS/MPACT', 'https://treasury.ms.gov/college-savings/', '["Prepaid and savings options"]', 'State tax deduction available', 'None'),
('MO', 'Missouri', true, 8000, 16000, false, null, 'MOST 529', 'https://www.missourimost.org/', '["Vanguard investment options"]', 'State tax deduction available', 'None'),
('MT', 'Montana', true, 3000, 6000, false, null, 'Achieve Montana', 'https://achievemontana.com/', '["Multiple investment options"]', 'State tax deduction available', 'None'),
('NE', 'Nebraska', true, 10000, 20000, false, null, 'NEST 529', 'https://www.nest529.com/', '["High deduction limits"]', 'State tax deduction available', 'None'),
('NV', 'Nevada', false, null, null, false, null, 'Nevada 529', 'https://www.nevadatreasurer.gov/529/', '["Vanguard options", "No state income tax"]', 'No state income tax to benefit from', 'None'),
('NH', 'New Hampshire', false, null, null, false, null, 'UNIQUE College Investing Plan', 'https://www.fidelity.com/529-plans/new-hampshire', '["Fidelity manages", "No state income tax"]', 'No state income tax to benefit from', 'None'),
('NJ', 'New Jersey', false, null, null, false, null, 'NJBEST', 'https://www.njbest.com/', '["Franklin Templeton manages"]', 'No state tax benefit currently', 'None'),
('NM', 'New Mexico', true, null, null, false, null, 'The Education Plan', 'https://www.theeducationplan.com/', '["Full state tax deduction"]', 'Unlimited state tax deduction', 'None'),
('NY', 'New York', true, 5000, 10000, false, null, 'NY 529 Direct Plan', 'https://www.nysaves.org/', '["Vanguard investment options", "Low fees"]', 'State tax deduction available', 'None'),
('NC', 'North Carolina', false, null, null, false, null, 'NC 529 Plan', 'https://www.nc529.org/', '["Multiple investment options"]', 'No state tax benefit currently', 'None'),
('ND', 'North Dakota', true, 5000, 10000, false, null, 'College SAVE', 'https://www.collegesave4u.com/', '["State tax deduction"]', 'State tax deduction available', 'None'),
('OH', 'Ohio', true, 4000, 4000, false, null, 'CollegeAdvantage', 'https://www.collegeadvantage.com/', '["Per beneficiary deduction"]', 'State tax deduction per beneficiary annually', 'Deduction is per beneficiary, not per taxpayer'),
('OK', 'Oklahoma', true, 10000, 20000, false, null, 'Oklahoma 529', 'https://www.ok4saving.org/', '["TIAA manages"]', 'State tax deduction available', 'None'),
('OR', 'Oregon', true, 2525, 5050, false, null, 'Oregon College Savings Plan', 'https://www.oregoncollegesavings.com/', '["TIAA manages"]', 'State tax deduction available', 'Subject to income limits'),
('PA', 'Pennsylvania', true, 16000, 32000, false, null, 'PA 529', 'https://www.pa529.com/', '["High deduction limits", "Per beneficiary"]', 'State tax deduction per beneficiary', 'Per beneficiary annual limit'),
('RI', 'Rhode Island', true, 500, 1000, false, null, 'CollegeBound Saver', 'https://www.collegeboundsaver.com/', '["Multiple investment options"]', 'State tax deduction available', 'None'),
('SC', 'South Carolina', true, null, null, false, null, 'Future Scholar', 'https://www.futurescholar.com/', '["Full state tax deduction"]', 'Unlimited state tax deduction', 'None'),
('SD', 'South Dakota', false, null, null, false, null, 'CollegeAccess 529', 'https://www.collegeaccess529.com/', '["No state income tax"]', 'No state income tax to benefit from', 'None'),
('TN', 'Tennessee', false, null, null, false, null, 'TNStars', 'https://www.tnstars.com/', '["No state income tax on wages"]', 'No state income tax on wages', 'None'),
('TX', 'Texas', false, null, null, false, null, 'Texas College Savings Plan', 'https://www.texascollegesavings.com/', '["No state income tax"]', 'No state income tax to benefit from', 'None'),
('UT', 'Utah', false, null, null, true, null, 'my529', 'https://my529.org/', '["5% tax credit on contributions up to certain limits"]', 'State tax credit available', 'Credit subject to limits'),
('VT', 'Vermont', false, null, null, true, null, 'Vermont Higher Education Investment Plan', 'https://www.vermontinvestmentplan.com/', '["10% tax credit on first $2,500"]', 'State tax credit instead of deduction', 'Credit limited to $250-$500'),
('VA', 'Virginia', true, 4000, 4000, false, null, 'Virginia529', 'https://www.virginia529.com/', '["Per account deduction", "Age 70+ higher limit"]', 'State tax deduction with higher limit for age 70+', 'Per account annual limit'),
('WA', 'Washington', false, null, null, false, null, 'DreamAhead', 'https://dreamahead.wa.gov/', '["No state income tax"]', 'No state income tax to benefit from', 'None'),
('WV', 'West Virginia', true, null, null, false, null, 'SMART529', 'https://www.smart529.com/', '["Full state tax deduction"]', 'Unlimited state tax deduction', 'None'),
('WI', 'Wisconsin', true, 3560, 7120, false, null, 'Edvest', 'https://www.edvest.com/', '["TIAA manages", "Per beneficiary deduction"]', 'State tax deduction per beneficiary', 'Per beneficiary annual limit'),
('WY', 'Wyoming', false, null, null, false, null, 'Wyoming 529 Plan', 'https://wyoming529plan.thecollegesavingsplan.info/', '["No state income tax"]', 'No state income tax to benefit from', 'None')
ON CONFLICT (state) DO NOTHING;